### ISSUE TITLE
npm run build don't work

### ISSUE THREAD

**Issue by wilfried11** [fullcalendar/typescript-example#1]
Hi @arshaw 
I am devloper beginer , i have clone the project and run npm install ; but when run : npm build , have this error in my console 

```
> ./node_modules/webpack/bin/webpack.js

**'.' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1**
npm ERR! fullcalendar-scheduler-typescript-example@1.0.0 build: `./node_modules/webpack/bin/webpack.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fullcalendar-scheduler-typescript-example@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    path/debug.log
```

thank's for any reply

**Comment by arshaw** [comment]
I'm curious, are you using cygwin? What OS?

I've made some changes. It should work now. Can you pull in master, try again, and let me know?

**Comment by wilfried11** [comment]
I'm using Win 10
I have clone it again test : get the same Error after run `npm build`

```
./node_modules/webpack/bin/webpack.js

'.' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fullcalendar-scheduler-typescript-example@1.0.0 build:
`./node_modules/webpack/bin/webpack.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fullcalendar-scheduler-typescript-example@1.0.0
build script.
npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!
 C:\Users\Rainbow-CL\AppData\Roaming\npm-cache\_logs\2018-02-05T09_29_47_110Z-debug.log
```

**Comment by arshaw** [comment]
are you sure you have the latest version? it doesn't look like you do. if you open up `package.json` it should look like this: https://github.com/fullcalendar/typescript-example/blob/449c70ce0e4e2b385814b396a930d4221fdea7d8/package.json#L23

note the build and the watch lines

**Comment by wilfried11** [comment]
I'm using angular CLI : 1.6.5
 Node : 8.9.4 and OS : win32 x64

**Comment by acerix** [comment]
The issue was fixed by https://github.com/fullcalendar/typescript-example/commit/449c70ce0e4e2b385814b396a930d4221fdea7d8. If you still get the error, check that you have the latest version.
